version: '3.8'
services:
  frontend:
    build: ./node
    container_name: react-frontend
    command: npm run dev
    networks:
      - frontend
    volumes:
      - ./node:/app
    ports:
      - 5173:5173

networks:
  frontend:
    driver: bridge
